# Generated by Django 3.2 on 2023-06-15 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acesso',
            options={'managed': False},
        ),
    ]
