# Generated by Django 3.2 on 2023-06-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_acesso_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acesso',
            table='acesso',
        ),
    ]
