# Generated by Django 3.2 on 2024-01-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_acesso_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acesso',
        ),
    ]
